---
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - ../vars/Provision.yml
  tasks:
  - name: Set volumes ID
    set_fact:
     ip_1: "{{ lookup('file', '../vars/ip_1-id.yml') }}"
     ip_2: "{{ lookup('file', '../vars/ip_2-id.yml') }}"

  - name: Check Infrastructure
    uri:
     url: "http://{{ item }}"
    with_items: 
     - "{{ ip_1 }}"
     - "{{ ip_2 }}"